- name: messgage-1
  ansible.builtin.debug:
    msg: "Hi from MSG-1"

- name: messgage-2
  ansible.builtin.debug:
    msg: "Hi from MSG-2"

- name: messgage-3
  ansible.builtin.debug:
    msg: "Hi from MSG-3"
