- name: message-1
  ansible.builtin.debug:
    msg: "Hi from MSG-1"
  when: os == "debian"    

- name: set the os fact
  ansible.builtin.set_fact:
    os: "RedHat"    

- name: message-2
  ansible.builtin.debug:
    msg: "Hi from MSG-2"

- name: message-3
  ansible.builtin.debug:
    msg: "Hi from MSG-3"
