- name: messgage-1
  ansible.builtin.debug:
    msg: "Hi from MSG-1"

- name: set the os fact
  ansible.builtin.set_fact:
    os: "RedHat"    

- name: messgage-2
  ansible.builtin.debug:
    msg: "Hi from MSG-2"

- name: messgage-3
  ansible.builtin.debug:
    msg: "Hi from MSG-3"
